#############################################################################
# Makefile for building: Snake
# Generated by qmake (3.1) (Qt 6.7.2)
# Project:  Snake.pro
# Template: app
# Command: C:\msys64\mingw64\bin\qmake6.exe -o Makefile Snake.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\msys64\mingw64\bin\qmake6.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\msys64\mingw64\bin\qmake6.exe -install qinstall
QINSTALL_PROGRAM = C:\msys64\mingw64\bin\qmake6.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = widl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Snake.pro C:/msys64/mingw64/share/qt6/mkspecs/win32-g++/qmake.conf C:/msys64/mingw64/share/qt6/mkspecs/features/spec_pre.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/device_config.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/common/sanitize.conf \
		C:/msys64/mingw64/share/qt6/mkspecs/common/gcc-base.conf \
		C:/msys64/mingw64/share/qt6/mkspecs/common/g++-base.conf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/common/windows-vulkan.conf \
		C:/msys64/mingw64/share/qt6/mkspecs/common/g++-win32.conf \
		C:/msys64/mingw64/share/qt6/mkspecs/common/windows-desktop.conf \
		C:/msys64/mingw64/share/qt6/mkspecs/qconfig.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_dbus.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designer.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_entrypoint_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_gui.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_help.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_help_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_linguist.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_network.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_network_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_opengl.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qml.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialport.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sql.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svg.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_testlib.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uitools.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_widgets.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_xml.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		C:/msys64/mingw64/share/qt6/mkspecs/features/qt_functions.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/qt_config.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/win32-g++/qmake.conf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/msys64/mingw64/share/qt6/mkspecs/features/exclusive_builds.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/toolchain.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/default_pre.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/win32/default_pre.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/resolve_config.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/exclusive_builds_post.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/default_post.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/qtquickcompiler.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/precompile_header.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/warn_on.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/permissions.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/qt.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/resources_functions.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/resources.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/moc.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/win32/opengl.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/uic.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/qmake_use.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/file_copies.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/win32/windows.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/testcase_targets.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/exceptions.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/yacc.prf \
		C:/msys64/mingw64/share/qt6/mkspecs/features/lex.prf \
		Snake.pro \
		C:/msys64/mingw64/lib/Qt6EntryPoint.prl \
		C:/msys64/mingw64/share/qt6/mkspecs/features/build_pass.prf
	$(QMAKE) -o Makefile Snake.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
C:/msys64/mingw64/share/qt6/mkspecs/features/spec_pre.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/device_config.prf:
C:/msys64/mingw64/share/qt6/mkspecs/common/sanitize.conf:
C:/msys64/mingw64/share/qt6/mkspecs/common/gcc-base.conf:
C:/msys64/mingw64/share/qt6/mkspecs/common/g++-base.conf:
C:/msys64/mingw64/share/qt6/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/msys64/mingw64/share/qt6/mkspecs/common/windows-vulkan.conf:
C:/msys64/mingw64/share/qt6/mkspecs/common/g++-win32.conf:
C:/msys64/mingw64/share/qt6/mkspecs/common/windows-desktop.conf:
C:/msys64/mingw64/share/qt6/mkspecs/qconfig.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_core_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_dbus.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designer.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designer_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_entrypoint_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_gui.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_gui_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_help.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_help_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_linguist.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_network.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_network_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_opengl.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qml.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qml_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quick_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialport.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_serialport_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sql.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_sql_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svg.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svg_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_testlib.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_tools_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uitools.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_widgets.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_xml.pri:
C:/msys64/mingw64/share/qt6/mkspecs/modules/qt_lib_xml_private.pri:
C:/msys64/mingw64/share/qt6/mkspecs/features/qt_functions.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/qt_config.prf:
C:/msys64/mingw64/share/qt6/mkspecs/win32-g++/qmake.conf:
C:/msys64/mingw64/share/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/msys64/mingw64/share/qt6/mkspecs/features/exclusive_builds.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/toolchain.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/default_pre.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/win32/default_pre.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/resolve_config.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/exclusive_builds_post.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/default_post.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/qtquickcompiler.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/precompile_header.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/warn_on.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/permissions.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/qt.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/resources_functions.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/resources.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/moc.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/win32/opengl.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/uic.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/qmake_use.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/file_copies.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/win32/windows.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/testcase_targets.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/exceptions.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/yacc.prf:
C:/msys64/mingw64/share/qt6/mkspecs/features/lex.prf:
Snake.pro:
C:/msys64/mingw64/lib/Qt6EntryPoint.prl:
C:/msys64/mingw64/share/qt6/mkspecs/features/build_pass.prf:
qmake: FORCE
	@$(QMAKE) -o Makefile Snake.pro -spec win32-g++ "CONFIG+=qtquickcompiler"

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

.SUFFIXES:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
